name: hello-world
on: 
   push: 
      branches: 
        - cloud5 

jobs:
  build:
   name: Hello world
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Run Dockerfile
      run: docker build . --tag my-app:55
