name: hello-world-example..
on: 
#   pull_request:
  push:
      types:
          -opened 
# [closed, synchronize, labeled]
      branches:
       - cloud1
#   push:
#      branches: 
#        - cloud1


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"
      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      -
        name: Say Goodbye
        run: echo "Goodbye!"
